### ISSUE TITLE
Plans for bioconda package?

### ISSUE THREAD

**Issue by Midnighter** [RAHenriksen/NGSNGS#25]
As the title says, do you plan to create a bioconda package for this tool? I think it that'd make it much more accessible.

**Comment by kabilov** [comment]
Absolutely agree. It would be very helpful.

**Comment by fgvieira** [comment]
`NGSNGS` is already in [bioconda](https://anaconda.org/bioconda/ngsngs).

**Comment by Midnighter** [comment]
Awesome!

**Comment by RAHenriksen** [comment]
Apologize for the late reply,

But this conda is from the release we made with the publication.

There will be some slight changes in the future, so we wont update this conda package until our new release

**Comment by RAHenriksen** [comment]
But i will look into the bioconda automatically updating itself whenever I make a new release, so I can do it a bit more often when solving the various bugs.

**Comment by Midnighter** [comment]
If the bioconda recipe installs from an official source, it should update automatically.
