### ISSUE TITLE
aborted (core dumped)

### ISSUE THREAD

**Issue by mxiong2** [RAHenriksen/NGSNGS#29]
-> ngsngs version: 9935075 (htslib: 1.17) build(May 12 2023 13:48:30)
	-> Mycommmand: /home/mai/NGSNGS/ngsngs -i cftr.fasta -r 1000 -f fq.gz -l 100 -seq SE -t 1 -ne -o test 
**ngsngs: NGSNGS.cpp:105: int main(int, char**): Assertion `((gz = gzopen(mypars->QualProfile1,"rb")))!=Z_NULL' failed**.
Aborted (core dumped)

**Comment by RAHenriksen** [comment]
Hi mxiong, 

If you're simulating fastq files, you need to also provide the quality profiles to generate the quality scores for each nucleotide , by adding the -q1 for single end reads

-q1 Test_Examples/AccFreqL150R1.txt

**Comment by RAHenriksen** [comment]
Dear mxiong, i have now in the latest commit included several error messages such that the user is made aware of the different cases depending on the required arguments.

Please let me know if you find any other cases
