### ISSUE TITLE
Unrecognized input option -qs, see NGSNGS help page

### ISSUE THREAD

**Issue by shanikawm** [RAHenriksen/NGSNGS#37]
Did you remove the -qs from the latest version?

**Comment by RAHenriksen** [comment]
Dear Shanikawn, no i haven't removed the -qs option.

I just tried running one of the examples provided by the helppage

`./ngsngs -i Test_Examples/Mycobacterium_leprae.fa.gz -r 100000 -t 1 -s 1 -lf Test_Examples/Size_dist_sampling.txt -ll 50 -seq SE -qs 40 -f fq -o MycoBactFqQsLlSEOut
`
with this version

	-> ngsngs version: bcf7a53 (htslib: 1.18-4-g5098983) build(Oct 10 2023 15:18:41)

When I run this I get a file with a few number of reads as such

@T0_RID36393_S0_NZ_CP029543.1:234384-234448_length:65_mod0000 F0 R1
GCAAGGTAGTTGGCAGTTACTGTATTAAAAAGTCGGCCCGCATGAAGCCGACATAGAGGAAGAGC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@T0_RID37465_S0_NZ_CP029543.1:203935-204017_length:83_mod0000 F0 R1
AAGAAATTGCTCATTAACAGATCGTGCATGCTGCCGATGCCATCGACAGTTGGCAAATCGTCGATAGGTTGGCTGAATCCGAT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

So it should still be working, could you provide med with both the command you're using and the standard print NGSNGS provides when running it? 

Best regards,
Rasmus

**Comment by shanikawm** [comment]
Hi, 
I think it is not available in the release. I just cloned the git and compiled it. It worked. You may have to do a fresh release. 

Thanks, 
Shanika

**Comment by ANGSD** [comment]
Dear @shanikawm can you provide more details regarding the issue otherwise we will close the issue.
