### ISSUE TITLE
sprintf warnings on clang

### ISSUE THREAD

**Issue by ANGSD** [RAHenriksen/NGSNGS#38]
´´´
fvr124@SUN1024817 ngsngs % make clean;make
Crypto library is not available to link; will not use -lcrypto
HTSSRC not defined, assuming systemwide installation -lhts
rm -f ngsngs *.o *.d version.h
rm -f test/*.fa test/*.fq test/*.sam test/*.txt
Crypto library is not available to link; will not use -lcrypto
HTSSRC not defined, assuming systemwide installation -lhts
echo '#define NGSNGS_VERSION "cc53c5c"' > version.h
c++ -c  -O3 -std=c++11   Briggs.cpp
c++ -MM -O3 -std=c++11   Briggs.cpp >Briggs.d
c++ -c  -O3 -std=c++11   Briggs2.cpp
c++ -MM -O3 -std=c++11   Briggs2.cpp >Briggs2.d
c++ -c  -O3 -std=c++11   HelpPage.cpp
c++ -MM -O3 -std=c++11   HelpPage.cpp >HelpPage.d
c++ -c  -O3 -std=c++11   NGSNGS.cpp
c++ -MM -O3 -std=c++11   NGSNGS.cpp >NGSNGS.d
c++ -c  -O3 -std=c++11   NGSNGS_cli.cpp
c++ -MM -O3 -std=c++11   NGSNGS_cli.cpp >NGSNGS_cli.d
c++ -c  -O3 -std=c++11   NGSNGS_misc.cpp
c++ -MM -O3 -std=c++11   NGSNGS_misc.cpp >NGSNGS_misc.d
c++ -c  -O3 -std=c++11   NtSubModels.cpp
c++ -MM -O3 -std=c++11   NtSubModels.cpp >NtSubModels.d
c++ -c  -O3 -std=c++11   RandSampling.cpp
c++ -MM -O3 -std=c++11   RandSampling.cpp >RandSampling.d
c++ -c  -O3 -std=c++11   Sampling.cpp
Sampling.cpp:430:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(READ_ID+strlen(READ_ID),"%d F%d",0,FragNo);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
Sampling.cpp:450:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(READ_ID+strlen(READ_ID),"%d F%d",has_seqerr,FragNo);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
2 warnings generated.
c++ -MM -O3 -std=c++11   Sampling.cpp >Sampling.d
c++ -c  -O3 -std=c++11   ThreadGeneration.cpp
ThreadGeneration.cpp:185:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
      sprintf(ref, "reference=%s", refSseq);
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 warning generated.
c++ -MM -O3 -std=c++11   ThreadGeneration.cpp >ThreadGeneration.d
c++ -c  -O3 -std=c++11   add_indels.cpp
add_indels.cpp:28:18: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
      offsetIns+=sprintf(InsOps+offsetIns,"[%d,%d:%d],",beg-cumlen,beg,len);
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
add_indels.cpp:43:18: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
      offsetDel+=sprintf(DelOps+offsetDel,"[%d,%d:%d],",beg+offset,beg-cumlen+offset,len);
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
2 warnings generated.
c++ -MM -O3 -std=c++11   add_indels.cpp >add_indels.d
c++ -c  -O3 -std=c++11   add_variants.cpp
c++ -MM -O3 -std=c++11   add_variants.cpp >add_variants.d
c++ -c  -O3 -std=c++11   fasta_sampler.cpp
c++ -MM -O3 -std=c++11   fasta_sampler.cpp >fasta_sampler.d
c++ -c  -O3 -std=c++11   getFragmentLength.cpp
c++ -MM -O3 -std=c++11   getFragmentLength.cpp >getFragmentLength.d
c++ -c  -O3 -std=c++11   mrand.cpp
c++ -MM -O3 -std=c++11   mrand.cpp >mrand.d
c++ -c  -O3 -std=c++11   sample_qscores.cpp
c++ -MM -O3 -std=c++11   sample_qscores.cpp >sample_qscores.d
c++ -O3  -o ngsngs *.o -lz -lm -lbz2 -llzma -lpthread -lcurl -lhts
´´´

**Comment by ANGSD** [comment]
fix like here
https://github.com/metaDMG-dev/metaDMG-cpp/commit/e3a3acdc3f0afe07c7c9afc56731e970c36953b3#diff-79c5c9be5c7452b8bba61de8e9df474da41351139a5d6de0d3b7acf03dbeeb1aL325-L326

**Comment by RAHenriksen** [comment]
done
