### ISSUE TITLE
NGSNGS needs a license

### ISSUE THREAD

**Issue by MikkelSchubert** [RAHenriksen/NGSNGS#44]
NGSNGS does not appear to be released under any license.

Strictly speaking, this means that

> no one may reproduce, distribute, or create derivative works from [NGSNGS].

<https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository>

In other words, nobody actually has permission to use NGSNGS at present.
I would therefore strongly recommend that you pick a license ASAP and add it to the repository.

The link above has more information and guidance on picking a license.

You will probably also need to consult people who have contributed source code to NGSNGS, since they likewise retain the rights to the code they've written. Should you accept the pull-request I submitted then you have my permission to re-license the code under whatever license you choose for NGSNGS. Assuming that the small amount of code I wrote actually necessitates that.

Best,
Mikkel

**Comment by RAHenriksen** [comment]
Hi Mikkel,

Thanks for your pull request we will look into it. And thanks for your concerns about the license, and the provided information, I will consult my other contributors.

Best regards,
Rasmus

**Comment by RAHenriksen** [comment]
Hi Mikkel,

Again thanks for your comments and we highly appreciate any input! At the moment we are still considering a potential license, but for now @ANGSD and I have agreed to keep NGSNGS as is.

I have merged the PR. But just to inform you or any other people who might watch this,  if you look at the changes to the bam_set1 function

https://github.com/RAHenriksen/NGSNGS/commit/26bee6a8d9d81e82f48f5bffdcc082e07e462b8e#diff-21eaccee84da8d6c5642f2b38f917e6eab4385234987baa58a276c73f906d789L540-L551

Then the same value ( chr_idx_read ) for the int32_t tid and int32_t mtid leads to the following warning when opening the single-end simulated sam file with samtools 

[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped

This is a result of the tid being defined as the chromosome for which we simulate data, but the mate for single-end should remain undefined, so they need to be distinct values. 

This was not detected in the make test, so I have also altered the test to accommodate further changes to the bam_set.

If you have other suggestions to update the bam_set function or other ideas while keeping the .sam format as is in terms of the md5sum, please let me know :-) .

Again thanks for your suggestions, and optimizations of older functions. I now consider this issue closed.

Cheers,
Rasmus

**Comment by MikkelSchubert** [comment]
Sorry about that, I appear to have misread the logic relating to chr_idx_mate when I wrote bd33237d43b6eaecf99c2ba07b36828f65a8bec1.

The fix should be relatively simple: Just re-add `int chr_idx_mate = -1;` at line 519 (line-numbers as shown in the commit), re-add the removed line 531 as `chr_idx_mate = chr_idx_read;`, and revert the changes from `chr_idx_mate` to `chr_idx_read` on lines 540 and 545.

But without a proper license I will not be touching the NGSNGS code-base any further, nor will I be using the tool, so I cannot test if these changes completely fix the issue.

**Comment by ajw2329** [comment]
Hello -- thanks for the great tool!  I just wanted to quickly second the request for a license given the implicit restrictions currently in place as mentioned by Mikkel.
